### ISSUE TITLE
dontbug on lxd

### ISSUE THREAD

**Issue by barl0g** [sidkshatriya/dontbug#11]
I have a problem with installation on lxd (debian).
What is this error?

```
$ dontbug record --server-listen 192.168.3.23 test/

[FATAL /home/roc/rr/rr/src/RecordSession.cc:1319:handle_signal_event() errno: SUCCESS] 
 (task 24353 (rec:24353) at time 1134)
 -> Assertion `false' failed to hold. Can't defer deterministic or internal signal {signo:SIGSEGV,errno:SUCCESS,code:SEGV_ACCERR,addr:0x7f99b2853080} at ip 0x7f99b4d83934
Launch gdb with 
  gdb '-l' '-1' '-ex' 'target extended-remote :24353' /usr/bin/php7.0
```

**Comment by sidkshatriya** [comment]
First you need to make sure `rr` works. What version of rr are you using?

Does the following work (recording and replaying `ls` )
```
rr record ls
rr replay
```

Are you on a virtual machine? If so what is the hypervisor? Are you on bare metal? Are you on AMD? (AMD does not work)

**Comment by barl0g** [comment]
> Does the following work (recording and replaying ls )

I think so.

```
(rr) continue
Continuing.
drupal  phpinfo.php  test

Program received signal SIGKILL, Killed.
0x0000000070000002 in ?? ()
(rr)
```

> Are you on a virtual machine?

On privileged LXD container.

> Are you on AMD

No. On Intel.

**Comment by sidkshatriya** [comment]
What version of rr are you on?

**Comment by barl0g** [comment]
```
$ rr --version
rr version 4.4.0
```

**Comment by sidkshatriya** [comment]
What about trying with rr version 4.5.0 ? https://github.com/mozilla/rr/releases

**Comment by barl0g** [comment]
Yes, I already tried rr 4.5.0 with the same results.
And with rr version 4.3 too.

**Comment by sidkshatriya** [comment]
What PHP script are you trying to record? Try recording a very very simple script first...

**Comment by rodion-k** [comment]
Solved for me by disabling opcache
