### ISSUE TITLE
Unhandled nmap

### ISSUE THREAD

**Issue by django23** [sidkshatriya/dontbug#2]
L.S.,

When fireing up everything looks great. When browsing to the url I get a `fatal error`

```
dontbug: Using config file:/home/xxx/.dontbug.yaml
dontbug: No <docroot-dir> argument provided. Assuming its the same as <php-source-root-dir>
dontbug: No --install-location specified. Defaulting to $GOPATH/src/github.com/sidkshatriya/dontbug
dontbug: Using --install-location "/home/xxx/.go/src/github.com/sidkshatriya/dontbug"
dontbug: Using php from path /usr/bin/php
dontbug: Using rr from path /usr/bin/rr
dontbug: Generating /home/xxx/.go/src/github.com/sidkshatriya/dontbug/ext/dontbug/dontbug_break.c for all PHP code in: /home/xxx/yyy/yyy-api/public
dontbug: 1 PHP files found
dontbug: Code generation complete. Compiling dontbug zend extension...
dontbug: Successfully ran 'make distclean' in dontbug zend extension directory
dontbug: Successfully ran phpize in dontbug zend extension directory
dontbug: Running configure in dontbug zend extension directory
dontbug: Successfully ran configure in dontbug zend extension directory
dontbug: Successfully compiled the dontbug zend extension
dontbug: -- Recording. Ctrl-C to terminate recording if running on the PHP built-in webserver
dontbug: -- Recording. Ctrl-C if running a script or simply wait for it to end

rr: Warning: Your CPU frequency governor is 'powersave'.  rr strongly
    recommends that you use the 'performance' governor.  Not using the
    'performance' governor can cause rr to be at least 2x slower
    on laptops.

    On Fedora-based systems, you can enable the 'performance' governor
    by running the following commands:

    $ sudo dnf install kernel-tools
    $ sudo cpupower frequency-set -g performance

rr: Saving execution to trace directory `/home/xxx/.local/share/rr/php-7'.
dontbug zend extension: dontbug.so successfully loaded by PHP
PHP 7.0.8-0ubuntu0.16.04.3 Development Server started at Thu Oct 13 12:32:13 2016
Listening on http://127.0.0.1:8088
Document root is /home/xxx/yyy/yyy-api/public
Press Ctrl-C to quit.
[FATAL /home/roc/rr/rr/src/util.cc:626:should_copy_mmap_region() errno: EACCES] Unhandled mmap /home/xxx/yyy/yyy-api/storage/framework/views/eb787bc5b0d00e38b5b2c5b312898d82c9820e4b.php(prot:0x1;SHARED); uid:33 mode:33188
dontbug: fatal error: base.go:428: record.go:207: signal: aborted
```

Do you have any clue? The directoy /home/xxx/yyy/yyy-api/storage/ has chmod 777

**Comment by sidkshatriya** [comment]
Some questions:
- Are you running in a Linux VM or on normal Linux?
- What does `$ rr --version` say ?
- You're using Ubuntu 16.04 right?
- How old is your laptop approximately?

Try doing the following as a test

```
$ rr record ls
$ rr replay
```

A gdb prompt should appear. Now type in `continue` followed by the enter key do you get the directory listing again? (This is exactly what is mentioned in https://github.com/sidkshatriya/dontbug/wiki/Installation-Instructions#testing-rr-and-gdb )

**Comment by sidkshatriya** [comment]
Also, did you build `rr` from source or did you just download the binary?

**Comment by sidkshatriya** [comment]
Basically I think there is a problem with `rr` and not Dontbug. So I'm going to ask you some additional questions to get enough information to troubleshoot this:
- What does `$ uname -a` say?
- Does Dontbug work if you do:

```
sudo apt-get install cpufrequtils
sudo cpufreq-set -g performance
```

(See https://github.com/mozilla/rr/wiki/Usage#getting-the-best-performance-on-your-machine-especially-laptops )
- What do you see if you do:

```
$ sudo apt install linux-tools-common
$ perf list
```
- What does the following command say?

```
$ cat /proc/sys/kernel/perf_event_paranoid
```

(See https://github.com/mozilla/rr/wiki/Building-And-Installing#hardwaresoftware-requirements )
- What does the following command say?

```
$ cat /proc/cpuinfo
```

**Comment by sidkshatriya** [comment]
@django23 As suggested by @khuey is user `xxx` the same user thats running the command? Probably want to make sure this is not some permissions issue.

(Though you mention that /home/xxx/yyy/yyy-api/storage/ is chmod 777 )

Better still... if the users are different -- can you try debugging a script in your home directory to eliminate a source of error?

Sorry if you're overwhelmed by the number of things we're requesting from you... :-)

**Comment by khuey** [comment]
If the permissions are 777 I would expect https://github.com/mozilla/rr/blob/master/src/util.cc#L578 to return true ...

**Comment by django23** [comment]
I reverted the changes, but wil try to send you al the information needed.

**Comment by sidkshatriya** [comment]
This issue has been closed as its been inactive for some time now. It can be reopened when there is more information.
