### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tbfisher** [sidkshatriya/dontbug#3]
After installing I get

```
# dontbug record /var/www/web/index.php
dontbug: No <docroot-dir> argument provided. Assuming its the same as <php-source-root-dir>
dontbug: No --install-location specified. Defaulting to $GOPATH/src/github.com/sidkshatriya/dontbug
dontbug: Using --install-location "/root/work/src/github.com/sidkshatriya/dontbug"
dontbug: Using php from path /usr/bin/php
dontbug: fatal error: base.go:428: base.go:317: Invalid Semantic Version
```

Install process seemed ok, except for symlinking xdebug headers, instead of

```
$ cd $GOPATH/github.com/sidkshatriya/dontbug
$ cd ext/dontbug
# create a symlink "xdebug" to the xdebug sources compiled earlier
$ ln -s ~/xdebug xdebug
```

I needed to

```
$ cd $GOPATH/src/github.com/sidkshatriya/dontbug
$ cd ext/dontbug
# create a symlink "xdebug" to the xdebug sources compiled earlier
$ ln -s ~/xdebug xdebug
```

**Comment by sidkshatriya** [comment]
Thanks... yes there should be a `src` there in the after $GOPATH. I've changed the installation instructions.

Regarding Invalid Semantic Version
what does 

```
$ /usr/bin/php --version
```

say for you?

**Comment by tbfisher** [comment]
```
# php --version
PHP 7.0.12-1+deb.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.2-dev, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by sidkshatriya** [comment]
Using your version string above I have been able to repeat this error locally. I'm working on a fix.

**Comment by sidkshatriya** [comment]
@tbfisher I think I've fixed this error. Try `go get` for dontbug and try again please?

**Comment by tbfisher** [comment]
Yes, that worked, thanks @sidkshatriya

**Comment by sidkshatriya** [comment]
@tbfisher Fantastic! Also, is Dontbug is working for you in the debugger? Are you able to do reverse debugging?

**Comment by sidkshatriya** [comment]
Closing this ticket as its reported to work by @tbfisher 

Would be interesting to know how the reverse debugging experience was for @tbfisher BTW. Would appreciate feedback...

**Comment by tbfisher** [comment]
@sidkshatriya works great -- I'm on a mac, running my application using docker via vmware fusion. I hit this issue: https://github.com/mozilla/rr/issues/1784

Reverse mode is significantly slower, but it's not bad.

**Comment by sidkshatriya** [comment]
Good to hear that things reverse mode is working well for you. Yes, reverse mode is going to be slower than normal mode.

Since you're using running within docker you must be running the docker `--privileged` mode right? In general, running in this mode is not recommended. e.g. See http://obrown.io/2016/02/15/privileged-containers.html  

> Don’t use privileged containers unless you treat them the same way you treat any other process running as root.

(There are other resources on the net on `--privileged` ... just google)

You should ideally just run Dontbug in a linux VM rather than in a docker container within a linux VM...
