### ISSUE TITLE
Error link to patch

### ISSUE THREAD

**Issue by sam002** [sidkshatriya/dontbug#7]
Install instruction, section [Installing (patched) Xdebug from source](https://github.com/sidkshatriya/dontbug/wiki/Installation-Instructions#installing-patched-xdebug-from-source)
Wget have link to html page: https://github.com/sidkshatriya/dontbug/blob/master/ext/dontbug/xdebug_2_4.make_extern.dontbug.patch
Correct link to raw: https://raw.githubusercontent.com/sidkshatriya/dontbug/master/ext/dontbug/xdebug_2_4.make_extern.dontbug.patch

**Comment by sidkshatriya** [comment]
Fixed. Thank you for reporting this!
